apiVersion: v1
kind: Secret
metadata:
  name: croustino-db
  labels:
    {{- include "croustino.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.utilisateur | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.motDePasse | quote }}
