apiVersion: v1
kind: ResourceQuota
metadata:
  name: plafond-croustino
  namespace: croustino
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "15"
    persistentvolumeclaims: "3"
